import {CODEX_POLL_MS,CODEX_STALE_MS} from '../codexTiming';
import {useEffect,useState} from 'react';
import {request} from '../api';
import {profile,scope} from '../session';
type Window={used_percent:number;duration_minutes:number;resets_at:number|null};
type Bridge={id:string;name:string;revoked_at:string|null;received_at:string|null;snapshot:null|{observed_at:string;status:string;buckets:{id:string;primary:Window|null;secondary:Window|null}[]}};
function windowName(minutes:number){return minutes%1440===0?`${minutes/1440} 天窗口`:`${minutes/60} 小时窗口`;}
export default function CodexConnections(){
 const key='hub_codex:'+scope();
 const[bridges,setBridges]=useState<Bridge[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'[]');}catch{return [];}});
 const[error,setError]=useState('');const[name,setName]=useState('我的电脑');const[busy,setBusy]=useState(false);const[token,setToken]=useState('');const[tick,setTick]=useState(Date.now());
 async function reload(){try{const data=await request<{bridges:Bridge[]}>('/api/v1/codex/bridges');localStorage.setItem(key,JSON.stringify(data.bridges));setBridges(data.bridges);setError('');}catch(e){setError('同步暂不可用，显示本机缓存；请检查网络或重新登录。');}}
 useEffect(()=>{let active=true;let loading=false;const controller=new AbortController();const update=async()=>{if(loading)return;loading=true;try{const data=await request<{bridges:Bridge[]}>('/api/v1/codex/bridges',{signal:controller.signal});if(active){localStorage.setItem(key,JSON.stringify(data.bridges));setBridges(data.bridges);setError('');}}catch(e){if(active)setError('同步暂不可用，显示本机缓存；请检查网络或重新登录。');}finally{loading=false;}};void update();const timer=setInterval(()=>{setTick(Date.now());void update();},CODEX_POLL_MS);return()=>{active=false;controller.abort();clearInterval(timer);};},[key]);
 async function connect(){setBusy(true);try{const data=await request<{token:string}>('/api/v1/codex/bridges',{method:'POST',body:JSON.stringify({name})});setToken(data.token);await reload();}catch(e){setError(String(e));}finally{setBusy(false);}}
 function download(){const blob=new Blob([JSON.stringify({server:profile().url,token,codex_path:'',interval_seconds:300},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='bridge.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function revoke(b:Bridge){if(!confirm('停止 '+b.name+' 的 Codex 上报？'))return;try{await request('/api/v1/codex/bridges/'+b.id,{method:'DELETE'});await reload();}catch(e){setError(String(e));}}
 return <section><div className="page-head"><div><p className="eyebrow">CODEX · LOCAL CONNECTION</p><h1>电脑上的 Codex，随时可见</h1><p className="lead">电脑采集额度摘要，手机自动接收。登录凭据和对话内容留在电脑。</p></div><button className="btn secondary" onClick={()=>void reload()}>刷新</button></div>
 <div className="sync-banner"><span className={'status-dot'+(error?' offline':'')}/><strong>{error?'离线缓存':'每 5 分钟同步'}</strong><span>电脑每 5 分钟采集 · 超过 11 分钟标为过期</span></div>
 {error&&<p role="status" className="error">{error}</p>}
 <div className="codex-grid">{bridges.map(b=>{const s=b.snapshot;const stale=!s||tick-new Date(s.observed_at).getTime()>CODEX_STALE_MS;return <article key={b.id} className="panel codex-card"><div className="page-head"><h2>{b.name}</h2><span className="device-tag">{b.revoked_at?'已撤销':!s?'等待电脑连接':s.status!=='ok'?'采集不可用':stale?'数据已过期':error?'缓存快照':'已连接'}</span></div><p className="muted compact">{s?'采集于 '+new Date(s.observed_at).toLocaleString():'启动电脑采集程序后，额度会显示在这里。'}</p>{s?.status==='unavailable'&&<p>请在电脑检查 Codex 登录状态及采集程序路径。</p>}{s?.buckets.map(bucket=><div key={bucket.id}><h3>{bucket.id}</h3>{[bucket.primary,bucket.secondary].filter((x):x is Window=>x!==null).map((w,i)=><div className="codex-window" key={i}><div><span>{windowName(w.duration_minutes)}</span><strong>{(100-w.used_percent).toFixed(0)}% <small>剩余</small></strong></div><progress aria-label={windowName(w.duration_minutes)+'剩余额度'} value={100-w.used_percent} max={100}/><p className="muted compact">已用 {w.used_percent}% · {w.resets_at?'重置于 '+new Date(w.resets_at*1000).toLocaleString():'重置时间未知'}</p></div>)}{!bucket.primary&&!bucket.secondary&&<p className="muted">此额度窗口暂不可用</p>}</div>)}{b.received_at&&<p className="muted compact">服务器接收于 {new Date(b.received_at).toLocaleString()}</p>}<button className="btn ghost" disabled={!!b.revoked_at} onClick={()=>void revoke(b)}>撤销此连接</button></article>})}</div>
 {!bridges.length&&<div className="empty-notes"><span className="empty-icon">↗</span><h2>连接第一台电脑</h2><p>先在电脑登录 Codex，再创建连接并启动采集程序。<br/>手机只需登录相同的 AI Hub 账户。</p></div>}
 <div className="panel" style={{marginTop:24}}><h2>添加电脑连接</h2><p className="muted">生成的配置只允许上报 Codex 摘要，可随时撤销。不会获得账户其他数据的读取权限。</p><label className="field"><span>电脑名称</span><input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><button className="btn primary" disabled={busy||!name.trim()} onClick={()=>void connect()}>生成连接配置</button>{token&&<div className="sync-banner"><span>配置仅在本次创建后提供，请下载并妥善保管。</span><button className="btn secondary" onClick={download}>下载 bridge.json</button><button className="btn ghost" onClick={()=>setToken('')}>隐藏配置</button></div>}<p className="muted compact">将 bridge.json 放入运行包的 bridge 文件夹，运行 Start-Codex-Bridge.ps1。Windows 脚本会自动查找 Codex 并限制配置文件访问。跨网络使用时，两端填写相同的 HTTPS 服务地址。</p></div></section>;
}
