import {useEffect,useState} from 'react';
import {Link,useSearchParams,useLocation} from 'react-router-dom';
import CodexPlanner from './CodexPlanner';
import {CODEX_NEWS_STALE_MS,CODEX_POLL_MS,CODEX_STALE_MS} from '../codexTiming';
import {request} from '../api';
import {scope} from '../session';
type Pref={enabled:boolean;near_hours:number;spare_percent:number;low_percent:number;pace_lead:number;credit_hours:number;cooldown_hours:number;quiet_start:number;quiet_end:number;utc_offset_minutes:number};
type Advice={kind:string;title:string;body:string;priority:number};
type Metric={bucket:string;slot:string;remaining:number;hours_left:number|null;rate_per_hour:number|null;daily_budget:number|null;resets_at:number|null;duration_minutes:number};
type Device={id:string;name:string;snapshot:any;history:any[];analysis:{state:string;metrics:Metric[];advice:Advice[]}};
type Alert={id:string;advice:Advice;first_seen:string;notified_at:string;dismissed:boolean;snoozed_until:string|null};
type Overview={generated_at:string;preferences:Pref;quiet:boolean;devices:Device[];alerts:Alert[];plan?:{plan_type:'plus'|'pro'|'unknown';source_type:string}};
const when=(v:string|number|null)=>v==null?'未知':new Date(typeof v==='number'?v*1000:v).toLocaleString();
const hours=(v:number|null)=>v==null?'时间未知':v<=0?'等待重置确认':v>=24?`${(v/24).toFixed(1)} 天`:`${v.toFixed(1)} 小时`;
const labels:Record<string,string>={slow:'建议放慢',use:'适合多用',balanced:'节奏平稳',stale:'等待新数据',unknown:'信息不足'};
const explain:Record<string,string>={slow:'保留后续任务的空间，先完成优先级最高的工作。',use:'把计划中的任务提前，充分使用本轮额度。',balanced:'额度与时间暂未触发提醒，按自己的工作节奏继续。',stale:'电脑可能离线或额度暂不可读，暂停节奏建议。',unknown:'额度窗口信息尚不完整，不推算可用余量。'};
function Trend({d,m}:{d:Device;m:Metric}){
 const points=d.history.flatMap(s=>{const w=s.buckets?.find((x:any)=>x.id===m.bucket)?.[m.slot];return w&&w.resets_at===m.resets_at?[{x:new Date(s.observed_at).getTime(),y:w.used_percent}]:[];});
 if(points.length<2)return <p className="muted compact">正在积累趋势样本，至少 15 分钟后尝试估算速度。</p>;
 const start=points[0].x,end=points[points.length-1].x;
 return <div className="trend"><svg viewBox="0 0 600 110" role="img" aria-label="本轮已用额度趋势，纵轴 0 到 100%"><path d="M10 15H590 M10 55H590 M10 95H590" stroke="currentColor" opacity=".1"/><polyline fill="none" stroke="var(--accent)" strokeWidth="2.5" points={points.map(p=>`${10+(p.x-start)/Math.max(1,end-start)*580},${95-p.y*.8}`).join(' ')}/><text x="12" y="12">100%</text><text x="12" y="108">0%</text></svg><div className="trend-axis"><span>{new Date(start).toLocaleTimeString()}</span><span>已用额度 · 最近最多 6 小时</span><span>{new Date(end).toLocaleTimeString()}</span></div></div>;
}
export default function CodexOverview(){
 const [params]=useSearchParams();const location=useLocation();
 const tabs=[['overview','额度总览'],['plan','使用计划'],['reminders','提醒中心'],['news','重置雷达'],['settings','提醒设置']];
 const requested=params.get('tab')||(location.hash==='#reminders'?'reminders':location.hash==='#rules'?'settings':'overview');
 const tab=tabs.some(t=>t[0]===requested)?requested:'overview';
 const [filter,setFilter]=useState('pending');
 const [strong,setStrong]=useState(localStorage.getItem('hub_advisor:'+scope()+':strong')!=='off');
 const key='hub_advisor:'+scope();
 const[data,setData]=useState<Overview|null>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null');}catch{return null;}});
 const[error,setError]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState('');
 const[editing,setEditing]=useState<Pref|null>(null),[saving,setSaving]=useState(false),[desktop,setDesktop]=useState(localStorage.getItem(key+':notify')==='on'),[clock,setClock]=useState(Date.now());
 async function reload(){try{const next=await request<Overview>('/api/v1/codex/overview');localStorage.setItem(key,JSON.stringify(next));setData(next);setError('');}catch{setError('服务暂不可用，显示上次缓存。已暂停桌面提醒。');}}
 useEffect(()=>{let alive=true,busy=false;const controller=new AbortController();const update=async()=>{if(busy)return;busy=true;try{const next=await request<Overview>('/api/v1/codex/overview',{signal:controller.signal});if(alive){localStorage.setItem(key,JSON.stringify(next));setData(next);setError('');}}catch{if(alive)setError('服务暂不可用，显示上次缓存。已暂停桌面提醒。');}finally{busy=false;}};void update();const timer=setInterval(()=>void update(),CODEX_POLL_MS);const clockTimer=setInterval(()=>setClock(Date.now()),60000);return()=>{alive=false;controller.abort();clearInterval(timer);clearInterval(clockTimer);};},[key]);
 useEffect(()=>{if(window.aihubDesktop||!data||error||!desktop||!data.preferences.enabled||data.quiet||!('Notification'in window)||Notification.permission!=='granted'||Date.now()-new Date(data.generated_at).getTime()>60000)return;
 void navigator.locks.request(key+':notify-lock',async()=>{for(const a of data.alerts){if((localStorage.getItem(key+':strong')!=='off'&&a.advice.kind!=='news')||a.dismissed||(a.snoozed_until&&new Date(a.snoozed_until).getTime()>Date.now()))continue;const k=key+':sent:'+a.id;if(localStorage.getItem(k)===a.notified_at)continue;new Notification(a.advice.title,{body:a.advice.body,tag:a.id});localStorage.setItem(k,a.notified_at);}}).catch(()=>setMessage('此浏览器暂不支持桌面通知，站内提醒仍然有效。'));
 },[data,error,desktop,key]);
 async function notify(){if(!('Notification'in window)){setMessage('此浏览器不支持系统通知，请使用站内提醒。');return;}if(desktop){localStorage.setItem(key+':notify','off');setDesktop(false);return;}if(await Notification.requestPermission()==='granted'){localStorage.setItem(key+':notify','on');setDesktop(true);}else setMessage('未获得通知权限；站内提醒继续显示。');}
 async function action(id:string,action:string){try{await request('/api/v1/codex/alerts/'+encodeURIComponent(id),{method:'POST',body:JSON.stringify({action})});await reload();}catch{setMessage('暂时无法更新提醒，请稍后重试。');}}
 async function save(){if(!editing)return;setSaving(true);try{await request('/api/v1/codex/preferences',{method:'PATCH',body:JSON.stringify(editing)});setEditing(null);setMessage('规则已保存，并同步到此账户。');await reload();}catch(e){setMessage(String(e));}finally{setSaving(false);}}
 async function savePlan(plan_type:string){try{await request('/api/v1/codex/plan',{method:'PUT',body:JSON.stringify({plan_type})});await reload();setMessage('套餐设置已保存；额度和提醒已重新计算。');}catch(e){setMessage(String(e));}}
 const d=data?.devices.find(x=>x.id===selected)||data?.devices[0];const stale=!!error||!d||clock-new Date(d.snapshot.observed_at).getTime()>CODEX_STALE_MS;const state=stale?'stale':d.analysis.state;
 const credits=d?.snapshot.reset_credits,news=d?.snapshot.news,p=editing||data?.preferences;
 const pending=(data?.alerts||[]).filter(a=>!a.dismissed&&(!a.snoozed_until||new Date(a.snoozed_until).getTime()<=clock));
 const alertState=(a:Alert)=>a.dismissed?'dismissed':a.snoozed_until&&new Date(a.snoozed_until).getTime()>clock?'snoozed':'pending';
 const visible=(data?.alerts||[]).filter(a=>alertState(a)===filter);
 const top=stale?undefined:[...(d?.analysis.advice||[])].filter(a=>a.kind!=="news").sort((a,b)=>b.priority-a.priority)[0];
 const fields:{key:keyof Pref;label:string;min:number;max:number;hint:string}[]=[
 {key:'near_hours',label:'临近重置 · 小时',min:1,max:168,hint:'同时不超过周期的最后 20%'},{key:'spare_percent',label:'多用提醒 · 剩余至少 %',min:10,max:95,hint:'其他窗口紧张时不催促多用'},
 {key:'low_percent',label:'低额度提醒 · 剩余不超过 %',min:1,max:30,hint:'优先于多用建议'},{key:'pace_lead',label:'超前消耗 · 百分点',min:5,max:70,hint:'已用比例超出时间进度的容许差'},
 {key:'credit_hours',label:'重置卡到期前 · 小时',min:1,max:168,hint:'仅对已知到期且仍可用的卡提醒'},{key:'cooldown_hours',label:'重复提醒间隔 · 小时',min:1,max:48,hint:'同一事件去重，也可手动忽略'},
 {key:'quiet_start',label:'免打扰开始 · 当地时',min:0,max:23,hint:'默认晚上 23 点'},{key:'quiet_end',label:'免打扰结束 · 当地时',min:0,max:23,hint:'默认早上 8 点；起止相同为关闭'},
 {key:'utc_offset_minutes',label:'时区 · UTC 偏移分钟',min:-720,max:840,hint:'北京时间 480；出差时可调整'}];
 return <section className="advisor"><header className="advisor-header"><div><p className="eyebrow">CODEX / PERSONAL COMPANION</p><h1>{({overview:'让额度跟上你的节奏',plan:'把剩余额度安排好',reminders:'把重要提醒处理好',news:'关注重置的最新动向',settings:'按你的习惯提醒'} as Record<string,string>)[tab]}</h1><p className="lead">{({overview:'什么时候多用一点，什么时候留一点，一眼就知道。',plan:'预留、分配、复盘，让下一次重置之前的工作更从容。',reminders:'集中处理额度、节奏和到期提醒，稍后提醒与忽略随时可恢复。',news:'查看 Tibo 原帖和最近检查结果，账户变化以实际采集为准。',settings:'统一管理规则阈值、免打扰时间和此设备的通知权限。'} as Record<string,string>)[tab]}</p></div><div className="advisor-tools">{data&&data.devices.length>1&&<select aria-label="分析哪台电脑" value={d?.id} onChange={e=>setSelected(e.target.value)}>{data.devices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<button className="btn secondary" onClick={()=>void reload()}>↻ 刷新</button></div></header>
 <div className="advisor-status"><span className={'status-dot'+(stale?' offline':'')}/><span>{stale?'等待电脑新数据':d?.name+' · 已同步'}</span><span>{d?.snapshot?.observed_at?when(d.snapshot.observed_at):'尚未采集'}</span><Link to="/connections">管理连接 ↗</Link></div>
 {error&&<p className="error" role="status">{error}</p>}{message&&<p className="sync-banner" role="status">{message}<button className="btn ghost" onClick={()=>setMessage('')}>关闭</button></p>}
 {data?.plan?.plan_type==='unknown'&&<p className="sync-banner">Codex 套餐尚未确认。请选择 Plus 或 Pro，以正确显示五小时额度。</p>}
 <label className="field"><span>Codex 套餐 · {data?.plan?.source_type==='manual'?'手动设置':'采集识别'}</span><select value={data?.plan?.plan_type||'unknown'} onChange={e=>void savePlan(e.target.value)}><option value="unknown">未知</option><option value="plus">Plus · 显示五小时额度</option><option value="pro">Pro · 隐藏五小时额度及提醒</option></select></label>
 <nav className="workspace-tabs" aria-label="Codex 功能标签">{tabs.map(([id,label])=><Link key={id} to={'/codex?tab='+id} aria-current={tab===id?'page':undefined}>{label}{id==='reminders'&&pending.length>0&&<span>{pending.length}</span>}</Link>)}</nav>
 {tab==='plan'&&<CodexPlanner device={d} stale={stale||state==='unknown'||state==='stale'}/>}
 {tab==='overview'&&(!data?.devices.length?<div className="empty-notes"><h2>先连接电脑上的 Codex</h2><p>真实额度到达后，自动生成节奏建议和到期提醒。</p><Link className="btn" to="/connections">连接电脑 ↗</Link></div>:<>
 <div className={'advice-hero '+state}><div><span className="advisor-kicker">现在的建议 · {labels[state]}</span><h2>{top?.title||labels[state]}</h2><p>{top?.body||explain[state]}</p><Link to="/codex?tab=reminders">查看提醒 →</Link></div><div className="hero-symbol" aria-hidden="true">{state==='slow'?'↘':state==='use'?'↗':state==='stale'?'◌':'≈'}</div></div>
 <div className="advisor-metrics">{d?.analysis.metrics.map((m,i)=><article className="quota-tile" key={m.bucket+m.slot}><div className="tile-caption"><span>{m.duration_minutes%1440===0?m.duration_minutes/1440+' 天':m.duration_minutes/60+' 小时'}额度</span><span>{m.bucket}</span></div><div className="quota-number">{m.remaining.toFixed(0)}<span>% 剩余</span></div><progress value={m.remaining} max={100} aria-label={m.bucket+'剩余额度'}/><div className="tile-row"><span>距离重置</span><strong>{hours(m.hours_left)}</strong></div><div className="tile-row"><span>均匀使用预算</span><strong>{m.daily_budget==null?'暂不可估':m.daily_budget.toFixed(1)+'% / 天'}</strong></div><p className="muted compact">{m.rate_per_hour==null?'样本不足，暂不预测耗尽时间':`近期消耗 ${m.rate_per_hour.toFixed(1)} 个百分点 / 小时`}</p>{i===0&&d&&<Trend d={d} m={m}/>}</article>)}
 <article className="quota-tile credit-tile"><div className="tile-caption"><span>备用重置卡</span><span>↺</span></div><div className="quota-number">{credits==null?'—':credits.available_count}<span>{credits==null?'状态未知':'张可用'}</span></div><p className="muted">{credits==null?'Codex 尚未返回重置卡信息。':credits.available_count===0?'当前没有可用的重置卡。':'接近到期时会单独提醒。只提醒，不自动兑换。'}</p>{credits?.items?.map((c:any)=><div className="credit-row" key={c.id}><span>重置卡</span><strong>{c.expires_at?when(c.expires_at)+' 到期':'到期时间未知'}</strong></div>)}{credits&&credits.available_count>credits.items.length&&<p className="muted compact">还有 {credits.available_count-credits.items.length} 张未返回到期明细。</p>}<p className="muted compact">是否满足兑换条件，以 Codex 中的实际提示为准。</p></article></div></>)}
 {tab==='reminders'&&<section className="panel" id="reminders"><div className="section-heading"><h2>值得留意</h2><span className="device-tag">{pending.length} 条提醒</span></div><p className="muted compact">{data?.quiet?'当前免打扰，站内仍展示，桌面不弹出。':'提醒已去重；可稍后 1 小时提醒，或忽略本次事件。'}</p>{!data?.preferences.enabled&&<p className="muted">提醒已暂停，分析仍更新。</p>}<div className="reminder-filters" aria-label="提醒状态">{[['pending','待处理'],['snoozed','稍后提醒'],['dismissed','已忽略']].map(([id,label])=><button key={id} className={'btn '+(filter===id?'':'secondary')} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label} · {(data?.alerts||[]).filter(a=>alertState(a)===id).length}</button>)}</div><p className="muted compact">显示仍符合触发条件的事件；已失效事件会自动移除。</p>{visible.length===0?<div className="calm-empty"><span>✓</span><h3>此分类暂无提醒</h3><p>临近重置、消耗过快、重置卡到期时会出现在这里。</p></div>:visible.map(a=><article className={'advice-item '+a.advice.kind} key={a.id}><div className="tile-caption"><span>{({slow:'节奏提醒',use:'额度利用',credit:'到期提醒',news:'外部消息'} as Record<string,string>)[a.advice.kind]}</span><time>{when(a.first_seen)}</time></div><h3>{a.advice.title}</h3><p>{a.advice.body}</p><div className="actions">{filter!=='pending'?<button className="btn secondary" onClick={()=>void action(a.id,'restore')}>恢复到待处理</button>:<><button className="btn secondary" onClick={()=>void action(a.id,'snooze')}>1 小时后提醒</button><button className="btn ghost" onClick={()=>void action(a.id,'dismiss')}>忽略本次</button></>}{filter==='snoozed'&&<span className="muted compact">{when(a.snoozed_until)} 恢复</span>}</div></article>)}</section>}
 {tab==='news'&&<section className="panel news-panel"><div className="section-heading"><h2>重置消息雷达</h2><a href="https://x.com/thsottiaux" target="_blank" rel="noreferrer">Tibo ↗</a></div><p className="muted">每 3 小时关注 @thsottiaux 的 Codex 重置相关原帖。</p><div className="news-status"><span className={'status-dot'+(!news||news.status!=='checked'||clock-new Date(news.checked_at).getTime()>CODEX_NEWS_STALE_MS?' offline':'')}/>{!news?'尚未检查':clock-new Date(news.checked_at).getTime()>CODEX_NEWS_STALE_MS?'检查记录已过期':news.status==='checked'?'已完成本次检查':'本次无法确认'}</div><p className="muted compact">{news?'上次尝试 '+when(news.checked_at):'每 3 小时检查结果将同步到这里。'}</p>{news?.items?.map((n:any)=><article className="news-item" key={n.url}><time className="muted compact">{n.approximate_time?"约 ":""}{when(n.published_at)}</time><p>{n.summary}</p><a href={n.url} target="_blank" rel="noreferrer">查看原帖 ↗</a></article>)}{news?.status==='checked'&&!news.items?.length&&<p>本次未发现可确认的新重置消息。</p>}<p className="muted compact">外部消息仅作参考，不修改账户额度或重置时间。无法访问来源时显示“无法确认”，不当作“没有消息”。</p></section>}
 {tab==='settings'&&p&&<section className="panel rules-panel" id="rules"><div className="section-heading"><div><h2>按你的习惯提醒</h2><p className="muted">规则跨端保存，通知权限仅在此设备生效。</p></div><button className="btn secondary" disabled={!!window.aihubDesktop} onClick={()=>void notify()}>{window.aihubDesktop?'已使用 App 原生弹窗':desktop?'关闭桌面提醒':'开启桌面提醒'}</button></div><div className="strong-settings"><label className="toggle-row"><input type="checkbox" checked={strong} onChange={e=>{setStrong(e.target.checked);localStorage.setItem(key+':strong',e.target.checked?'on':'off');}}/>启用强提醒弹窗（此设备）</label><p className="muted compact">额度过快、临近重置和卡片到期时弹出，处理后按冷却间隔去重。遵守免打扰；外部新闻不弹强提醒。Windows App 可在托盘运行时弹出，网页仅在打开期间有效。</p><div className="actions"><button className="btn secondary" onClick={()=>window.dispatchEvent(new Event('aihub-test-alert'))}>测试强提醒</button>{window.aihubDesktop&&<button className="btn secondary" onClick={()=>void window.aihubDesktop?.openCodex().catch(()=>setMessage('无法打开 Codex，请从开始菜单启动。'))}>打开 Codex 手动停止任务</button>}</div></div><label className="toggle-row"><input type="checkbox" checked={p.enabled} onChange={e=>setEditing({...p,enabled:e.target.checked})}/>启用额度与到期提醒</label><details open><summary>调整规则阈值与免打扰时间</summary><div className="rule-fields">{fields.map(f=><label className="field" key={f.key}><span>{f.label}</span><input type="number" min={f.min} max={f.max} value={p[f.key] as number} onChange={e=>setEditing({...p,[f.key]:Number(e.target.value)})}/><small className="muted">{f.hint}</small></label>)}</div></details>{editing&&<div className="actions"><button className="btn" disabled={saving} onClick={()=>void save()}>保存规则</button><button className="btn ghost" onClick={()=>setEditing(null)}>取消</button></div>}<p className="muted compact">普通浏览器通知需要系统权限。App 原生强提醒无需网页通知权限，关闭窗口后在托盘继续运行；退出 App、电脑休眠或服务离线时不能送达。移动端后台推送尚未配置。</p></section>}
 </section>;
}
